### ISSUE TITLE
Add info for [Path To Nowhere] (America, Europe, Asia-Pacific | English)

### ISSUE THREAD

**Issue by GameTimeMasterForm** [cicerakes/Game-Time-Master#295]
- **Game:** Path To Nowhere
- **Server region/language:** America, Europe, Asia-Pacific | English
- **Server timezone (location or offset):** America (UTC-7), Europe (UTC-2), Asia (UTC+7)
- **Server daily reset time:** (GMT+3) America 3PM, Europe 6AM, Asia 1AM
- **(Optional) Does the server reset time change during the server's daylight savings?** Unsure

**Comment by KinamiChoi** [comment]
hello ! i was the one that submitted this i would like to inform you that while searching more it seems the server does change with daylights savings for the NA server users only

**Comment by cicerakes** [comment]
> hello ! i was the one that submitted this i would like to inform you that while searching more it seems the server does change with daylight savings (for NA server players only)

This shouldn't be possible as the servers use an offset (UTC-7), and not a timezone (such as a location).  
To be clear, "server reset time change during the server's daylight savings" is when daylight savings applies to the server itself, and NOT your local reset time changing due to daylight savings. Daylight savings do not apply to offsets, which is what makes it impossible.

Regardless, thanks for trying to clarify your submission.
